### ISSUE TITLE
Getting an error on iOs 9

### ISSUE THREAD

**Issue by elearningatbath** [moodlehq/moodlemobile-phonegapbuild#18]
I'm getting this error only on iOs 9 when running the app built from Phonegap Build. It works fine for Android . 
![img_0009](https://cloud.githubusercontent.com/assets/7943580/10673155/3d9923fa-78ec-11e5-83df-da72d2879cba.PNG)

i also ran a safari debug and this is what i see ..

Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D

Would you why this would be happening ??? 

Thanks

**Comment by dpalou** [comment]
Hello,

have you modified the code of the app?

Regards,
Dani

**Comment by hitteshahuja** [comment]
Hello Dani,
Updating the code to 2.4 fixed it :laughing: .  
Thank you for your swift response
