### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by sam-suresh** [moodlehq/moodlemobile-phonegapbuild#23]
I build this source in phonegap and get the following error after apk is installed in Android. 
 
{{mma.files.myprivatefiles'|translate}} ... 

See image screenshot: 
https://drive.google.com/file/d/0B3Fc5SkBcZxxOTVWRV95VGk5TmdKaTZuci1IUHk0YTd3M0tR/

What is wrong?

Thanks

**Comment by dpalou** [comment]
Hello Sam,

if you're manually building the apk (without using Phonegap Build) you'll have to install all the dependencies to make it work. Please see: https://docs.moodle.org/dev/Setting_up_your_development_environment_for_Moodle_Mobile_2

If you don't want to use Phonegap Build then I recommend you to use this repository instead:

https://github.com/moodlehq/moodlemobile2

Kind regards,
Dani

**Comment by sam-suresh** [comment]
Thanks a lot for the reply.
I'm trying to replace resources and change login URLs.
Tried with moodlemobile2, same error.
This is the sequence:
1. Forked.
2. Changed info
3. Uploaded to PhoneGap build.

Thanks

**Comment by dpalou** [comment]
When you modify the source code (in www/addons or www/core folders) you need to run **gulp** so the changes are applied to the build files. We use development files to make code easier to understand, but then we use build files (www/build folder) to prevent having to include dozens of files in the index.

Please let me know if this fixes the issue for you.

Kind regards,
Dani

**Comment by sam-suresh** [comment]
Thanks. That was really helpful. 
I will install all necessary first.
Thanks

**Comment by ravishel** [comment]
So how do i solve this error ?
