### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by tigerssh** [moodlehq/moodlemobile-phonegapbuild#3]
Sorry, download the project and build in https://build.phonegap.com/ and apparently it has problems to android.

Thanks!

**Comment by andres-alvarez** [comment]
The solution that worked for me is the following:

1- Open config.xml

2- Remove the line  <gap:plugin name="com.phonegap.plugins.pushplugin" /> possibly the plugin is discontinued.

Thanks!

**Comment by wiotadmin** [comment]
Yep, getting the app crash straight after the splash screen.

**Comment by RekhaC** [comment]
The course Search icon does not show in learn moodle, whereby the entire course list gets downloaded in the app on sign-up and users can search for courses in the app and enrol (eg. to free guest courses or self-enrol). Have i got this missing feature right? Or, am I doing something wrong in building my app - i just added custom app site urls? It was missing in 2.9.3 version. Is the Search bar there in 3.1 version? If not, how can it be added? The search bar shows in the official moodle mobile app.
