### ISSUE TITLE
App forcing HTTPS on site url

### ISSUE THREAD

**Issue by lucassmuller** [moodlehq/moodlemobile-phonegapbuild#38]
Hello, i'm building a App to my Moodle with this repo. I set my 'siteurl' on config.json without HTTPS but when the login loads, it but the S, being HTTPS, that my website didn't support.
I tried to find a way to disable this 'forcing' but I didn't find.
How can I do that? Anwser please, it is really important.

**Comment by jleyva** [comment]
Please, use the forum support for this type of questions:
https://moodle.org/mod/forum/view.php?id=7798
