### ISSUE TITLE
siteurl didnt work

### ISSUE THREAD

**Issue by slamonega** [moodlehq/moodlemobile-phonegapbuild#41]
I put specific url to access a moodle site and didnt work, I follow the specific guidelines, but the app after compiling the APK is showing the step open to put the url site.

**Comment by slamonega** [comment]
Juan, disculpa mi ingles, el tema es que en el config.json pongo el siteurl, pero la app no me lo toma.

**Comment by mustafaameen** [comment]
I have the same problem.

**Comment by dpalou** [comment]
Please make sure to use "gulp" to build your changes, or apply the changes directly to the built file (build/mm.bundle.js).

The app uses a single javascript file with all of its code in it. This is to prevent having to include more than a hundred files in the index.html. To build this file we use "gulp". You can read more about this in this guide:

https://docs.moodle.org/dev/Setting_up_your_development_environment_for_Moodle_Mobile_2

If you don't want to set up your environment, then you need to apply the changes directly to build/mm.bundle.js. In case of the fixed siteurl, you need to add it in the constant named "mmCoreConfigConstants".

You should use the forum for this kind of questions, you'll probably get faster responses :)

Cheers,
Dani

**Comment by slamonega** [comment]
Dani, I am using this repository https://github.com/moodlehq/moodlemobile-phonegapbuild , because I directly work from Github to Phonegap Build, so I didnt use the Android Studio.

It is possible to resolve this situation from here or I will have to use the other repository?

Thank you!!

Sebas

**Comment by dpalou** [comment]
Hi Sebas,

like I said before:

If you don't want to set up your environment, then you need to apply the changes directly to build/mm.bundle.js. In case of the fixed siteurl, you need to add it in the constant named "mmCoreConfigConstants".

The file used by the app is "mm.bundle.js", so if you apply your changes directly to that file then you should see the results.

**Comment by slamonega** [comment]
gràcies Dani

**Comment by slamonega** [comment]
Dani, necesito resolver el tema del SiteURL desde Github.

desde el Build/mm.bundle.js

veo esto.

};
        self.createSiteID = function(siteurl, username) {
        return md5.createHash(siteurl + username);
    };
        function determineService(siteurl) {
        siteurl = siteurl.replace("https://", "http://");
        if (services[siteurl]) {
            return services[siteurl];
        }
        siteurl = siteurl.replace("http://", "https://");
        if (services[siteurl]) {
            return services[siteurl];
        }
        return mmCoreConfigConstants.wsservice;
    }
        function isValidMoodleVersion(infos) {
        if (!infos) {
            return false;
        }
        var minVersion = 2012120300,
            minRelease = "2.4";
        if (infos.version) {
            var version = parseInt(infos.version);
            if (!isNaN(version)) {
                return version >= minVersion;


Como lo tengo que poner, porque me viene tirando error.

Te agradezco la ayuda.
seba

**Comment by dpalou** [comment]
Hi Seba,

I'm answering in English so everybody can understand my answer and it can help other people.

You need to add the _siteurl_ in the **declaration** of _mmCoreConfigConstants_. It's usually at the end of the _build/mm.bundle.js_ file and it's something like this:

```
angular.module('mm.core')

.constant('mmCoreConfigConstants', {
    "app_id" : "com.moodle.moodlemobile",
    "appname": "Moodle Mobile",
    "versioncode" : "2015",
    "versionname" : "3.1.3",
    "cache_expiration_time" : 300000,
    "default_lang" : "en",
    "languages": {...},
    "wsservice" : "moodle_mobile_app",
    "wsextservice" : "local_mobile",
    "demo_sites": {...},
    "gcmpn": "694767596569"
}
);
```

You just have to add a new property in there:

```
    "gcmpn": "694767596569",
    "siteurl": "http://myfakeurl.com"
```

Kind regards,
Dani

**Comment by slamonega** [comment]
Thanks Dani! 
my best regards,
Sebas

**Comment by nguyendinhse** [comment]
apple reject my app 
please help me 

Performance - 2.5.4
  Your app declares support for audio in the UIBackgroundModes key in your Info.plist, but we were unable to play any audible content
