### ISSUE TITLE
Compatability of custom app and Website versions

### ISSUE THREAD

**Issue by RekhaC** [moodlehq/moodlemobile-phonegapbuild#57]
Hi,

How are different mobile app [custom app from Github] and website versions compatible?

My moodle website is 2.9.3 and custom mobile app is also 2.9.3. 

I want to upgrade but the web host is offering autoupgrade to 3.2.1 {a version's features i want]. The Github app version learn moodle respository is 3.1.2  https://github.com/moodlehq/moodlemobile-phonegapbuild/tree/learn-moodle .

1) Suppose I build my custom app from github in 3.1.2 and upgrade moodle website to 3.2.1, will they be compatible?

2) Is custom app 2.9.3 compatible with website 3.2.1?

Github has a lag in new versions, but the web host offers the latest verison. When is Github offering 3.2.1 in learnmoodle?

**Comment by moodlemobile** [comment]
Moodle Mobile is compatible with Moodle 2.4 onwards, no matter the version. We take care of making the app compatible with all versions since 2.4
