### ISSUE TITLE
apple reject my app please help me?

### ISSUE THREAD

**Issue by nguyendinhse** [moodlehq/moodlemobile-phonegapbuild#72]
Performance - 2.5.4
  Your app declares support for audio in the UIBackgroundModes key in your Info.plist, but we were unable to play any audible content

**Comment by santosleonardo** [comment]
I had the same problem. I am using the code from version 3.2.1.

**Comment by dpalou** [comment]
Moodle Mobile 3.2.1 includes a new Cordova plugin to support playing audio in background. You just need to put an audio file in your test course so Apple can test this.
